### ISSUE TITLE
Surface Zone GateB Elevator wall is little to far

### ISSUE THREAD

**Issue by Saskyc** [VirtualBrightPlayz/SLCloneIssues#67] opened 2024-01-13 20:12 UTC
![obrázek_2024-01-13_211146481](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/136163441/25630d88-826c-4de8-b80e-6abc6b28420b)
![obrázek_2024-01-13_211159061](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/136163441/7b0215c0-9cb7-4368-85c9-5a36ef5ae1a4)

**Comment by VirtualBrightPlayz** [comment] 2024-01-14 17:37
Dupe of #39

**Closed as completed by VirtualBrightPlayz** 2024-01-14 17:37 UTC
Labels: bug
